version: '3.8'
services:
 next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_FIREBASE_API_KEY=your-firebase-api-key
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=your-firebase-project-id
      - NEXT_PUBLIC_FIREBASE_APP_ID=your-firebase-app-id